### ISSUE TITLE
gradlew unpack error on Ubuntu 20.04.1

### ISSUE THREAD

**Issue by liugang** [cfig/Android_boot_image_editor#49]
```
$ ./gradlew unpack 

> Task :bbootimg:compileKotlin FAILED
e: /tmp/Android_boot_image_editor/bbootimg/src/main/kotlin/bootimg/cpio/AndroidCpio.kt: (251, 33): Unresolved reference: readAllBytes
e: /tmp/Android_boot_image_editor/bbootimg/src/main/kotlin/bootimg/cpio/AndroidCpio.kt: (252, 30): Overload resolution ambiguity: 
public inline fun String(stringBuffer: StringBuffer): String defined in kotlin.text
public inline fun String(stringBuilder: StringBuilder): String defined in kotlin.text
public inline fun String(bytes: ByteArray): String defined in kotlin.text
public inline fun String(chars: CharArray): String defined in kotlin.text
e: /tmp/Android_boot_image_editor/bbootimg/src/main/kotlin/bootimg/cpio/AndroidCpio.kt: (259, 44): Overload resolution ambiguity: 
public inline fun String(stringBuffer: StringBuffer): String defined in kotlin.text
public inline fun String(stringBuilder: StringBuilder): String defined in kotlin.text
public inline fun String(bytes: ByteArray): String defined in kotlin.text
public inline fun String(chars: CharArray): String defined in kotlin.text
e: /tmp/Android_boot_image_editor/bbootimg/src/main/kotlin/bootimg/cpio/AndroidCpio.kt: (260, 56): Overload resolution ambiguity: 
public inline fun String(stringBuffer: StringBuffer): String defined in kotlin.text
public inline fun String(stringBuilder: StringBuilder): String defined in kotlin.text
public inline fun String(bytes: ByteArray): String defined in kotlin.text
public inline fun String(chars: CharArray): String defined in kotlin.text

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bbootimg:compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
1 actionable task: 1 executed
```

cat /etc/issue
Ubuntu 20.04.1 LTS

java --version
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode)

b108110dbd6d5d74bd57285cf988790782741efd

**Comment by cfig** [comment]
Really strange.
It works fine on my local Ubuntu 20.04 + openjdk 11 ,and it also passed Travis CI auto test.
Can you have a try with latest "bin" branch to see if the binary version(compiled jar) works or not ?

**Comment by liugang** [comment]
I have the same problem on all 3 of my ubuntu, and I don’t know why after looking at it. Later I used other tools, so let’s do this. If someone else has the same problem, they don’t need to raise the issue again.

**Comment by cfig** [comment]
can you please run `./gradlew build --scan` and paste the last line of the running result?

**Comment by liugang** [comment]
https://scans.gradle.com/s/5h6trt3nmc2dg

**Comment by liugang** [comment]
I soloved this issue by: 
```
unset CLASSPATH
unset JAVA_HOME
```

I had install oracle jdk1.8.0_221

**Comment by cfig** [comment]
That's good.
build scan shows "Oracle Java(TM) SE Runtime Environment 1.8.0_221-b11", that's the point.

**Comment by bgman111111** [comment]
still dont work https://gradle.com/s/mxss2ngay3efa
